#!/bin/bash

rm a.out
g++ -O4 main.cpp
echo "---new compilation has been done"
dirstring="/home/cenna/Results/Close/sphere9G_r40_old_s2_delt0.1/"
mkdir $dirstring

cp main.cpp $dirstring

./a.out $dirstring
 
