// distributes particles in randomly
//#include "ParticleDistro.h"
#include <math.h>
#include <stdio.h>
#include <stdlib.h>
#include <iostream>
#include <time.h>

//#include "sphere.h"
#include "sphere.cpp"
// #include "peribc.cpp"
using namespace std;

double *ParticleDistro(int mboxsize, int nboxsize, int kboxsize, double Pf, int Pr)
{ 
    cout <<"particles fraction=" << Pf <<endl;

  int particlesn=int(Pf*double(mboxsize*nboxsize*kboxsize)/(4.0/3.0*3.1415*double(Pr*Pr*Pr))); // number of particles
  // cout <<"Number of particles are" << particlesn << endl;
  
  int nn,ii,jj,kk; //random indexes
  int i,j,k; // loops
  int iind,jind,kind; //periodic indexes
  double irand,jrand,prand, krand;
  double *ppfi;
  double *sphi;
  sphi=sphere(Pr);
  ppfi=new double[mboxsize*nboxsize*kboxsize];
  for (k=0;k<kboxsize;k++)
  {
    for (j=0;j<nboxsize;j++)
    {
      for (i=0;i<mboxsize;i++)
      {
        ppfi[i+j*mboxsize+k*mboxsize*nboxsize]=0;
      }
    }
  }
  cout <<"particles number=" << particlesn <<endl;
  // if Pf is negative then it mean there is only one particle in the middle
  if (particlesn <0){
    
    // 0.1* mboxsize is initial position of the interface + particle radius + interface thickness threshold
    ii=int(0.1*mboxsize+Pr+20);
    jj=int(mboxsize/2);
    kk=int(kboxsize/2);
    for (i=-Pr;i<Pr+1;i++)
    {
      iind=peribc(ii+i,mboxsize);
      for (j=-Pr;j<Pr+1;j++)
      {
        jind=peribc(jj+j,mboxsize);
        for (k=-Pr;k<Pr+1;k++)
        {
          kind=peribc(kk+k,mboxsize);
          ppfi[(iind)+(jind)*mboxsize+(kind)*mboxsize*nboxsize]=sphi[(i+Pr)+(j+Pr)*2*Pr+(k+Pr)*2*Pr*2*Pr];
        }
      }
    }
  }
  else{
    srand ( time(NULL) );
    for (nn=0;nn<particlesn;nn++){
      irand=rand();
      jrand=rand();
      krand=rand();
      prand=rand();
      // these are random index of the top corner of a box contaning the particle.
      // The box is generated by sphere.cpp 
      ii=int((nboxsize*irand)/RAND_MAX);
      jj=int((mboxsize*jrand)/RAND_MAX);
      kk=int((kboxsize*krand)/RAND_MAX);
      for (i=-Pr;i<Pr+1;i++)
      {
        iind=peribc(ii+i,mboxsize);
        for (j=-Pr;j<Pr+1;j++)
        {
          jind=peribc(jj+j,mboxsize);
          for (k=-Pr;k<Pr+1;k++)
          {
            kind=peribc(kk+k,mboxsize);
            ppfi[(iind)+(jind)*mboxsize+(kind)*mboxsize*nboxsize]=sphi[(i+Pr)+(j+Pr)*2*Pr+(k+Pr)*2*Pr*2*Pr]+ppfi[(iind)+(jind)*mboxsize+(kind)*mboxsize*nboxsize];
            if (ppfi[(iind)+(jind)*mboxsize+(kind)*mboxsize*nboxsize]>1)
              ppfi[(iind)+(jind)*mboxsize+(kind)*mboxsize*nboxsize]=1;
          }
        }
      }
    }
  }
  return ppfi;
}
