#!/bin/sh

source /opt/intel/Compiler/11.1/073/bin/iccvars.sh intel64
icpc -O3 -openmp -o icpcout energy.cpp

./icpcout /home/magnetadmin/Documents/Results/3D/Big/10/input.txt 1000
./icpcout /home/magnetadmin/Documents/Results/3D/Big/20/input.txt 1000
./icpcout /home/magnetadmin/Documents/Results/3D/Big/30/input.txt 1000
./icpcout /home/magnetadmin/Documents/Results/3D/Big/40/input.txt 1000
./icpcout /home/magnetadmin/Documents/Results/3D/Big/50/input.txt 1000
./icpcout /home/magnetadmin/Documents/Results/3D/Big/60/input.txt 1000
./icpcout /home/magnetadmin/Documents/Results/3D/Big/70/input.txt 1000
./icpcout /home/magnetadmin/Documents/Results/3D/Big/80/input.txt 1000
./icpcout /home/magnetadmin/Documents/Results/3D/Big/90/input.txt 1000

